//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tp2bd2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tp2bd2Entities : DbContext
    {
        public tp2bd2Entities()
            : base("name=tp2bd2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Candidature> Candidatures { get; set; }
        public virtual DbSet<Compagny> Compagnies { get; set; }
        public virtual DbSet<Cv> Cvs { get; set; }
        public virtual DbSet<Etudiant> Etudiants { get; set; }
        public virtual DbSet<log> logs { get; set; }
        public virtual DbSet<Personne> Personnes { get; set; }
        public virtual DbSet<Stage> Stages { get; set; }
        public virtual DbSet<Superviseur> Superviseurs { get; set; }
        public virtual DbSet<Telephone> Telephones { get; set; }
        public virtual DbSet<Types_Telephones> Types_Telephones { get; set; }
    }
}
